[package]
name = "strawberry_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aery = "0.5.2"
bevy = "0.12.1"
iter_tools = "0.4.0"
nalgebra = "0.32.3"
